"use strict";
exports.__esModule = true;
var vector_1 = require("./vector");
var vectorPrueba = new vector_1.Vector(5, 8);
var vectorDos = new vector_1.Vector(5, 9);
var vectorTres = new vector_1.Vector(0, 0);
vectorPrueba.print();
vectorTres = vectorPrueba.add(vectorDos);
vectorTres.print();
vectorTres = vectorPrueba.subs(vectorDos);
vectorTres.print();
vectorTres = vectorPrueba.mult(vectorDos);
vectorTres.print();
vectorTres = (vectorPrueba.multNumber(8));
vectorTres.print();
